# Generated by Django 3.0.1 on 2019-12-23 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='uid',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
