# Generated by Django 3.0.1 on 2019-12-23 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_choice_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='uid',
            field=models.CharField(editable=False, max_length=16, null=True),
        ),
    ]
